// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: public_api_down.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_public_5fapi_5fdown_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_public_5fapi_5fdown_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "public_api_types.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_public_5fapi_5fdown_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_public_5fapi_5fdown_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_public_5fapi_5fdown_2eproto;
class APIDown;
struct APIDownDefaultTypeInternal;
extern APIDownDefaultTypeInternal _APIDown_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::APIDown* Arena::CreateMaybeMessage<::APIDown>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class APIDown final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:APIDown) */ {
 public:
  inline APIDown() : APIDown(nullptr) {}
  ~APIDown() override;
  explicit constexpr APIDown(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  APIDown(const APIDown& from);
  APIDown(APIDown&& from) noexcept
    : APIDown() {
    *this = ::std::move(from);
  }

  inline APIDown& operator=(const APIDown& from) {
    CopyFrom(from);
    return *this;
  }
  inline APIDown& operator=(APIDown&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const APIDown& default_instance() {
    return *internal_default_instance();
  }
  enum DownCase {
    kBaseCommand = 1,
    kLinearLiftCommand = 2,
    kArmCommand = 3,
    kRotateLiftCommand = 4,
    kSetReportFrequency = 5,
    kSecondaryDeviceCommand = 7,
    kEnableKcp = 8,
    kPlaceholderMessage = 100,
    DOWN_NOT_SET = 0,
  };

  static inline const APIDown* internal_default_instance() {
    return reinterpret_cast<const APIDown*>(
               &_APIDown_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(APIDown& a, APIDown& b) {
    a.Swap(&b);
  }
  inline void Swap(APIDown* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(APIDown* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  APIDown* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<APIDown>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const APIDown& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const APIDown& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(APIDown* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "APIDown";
  }
  protected:
  explicit APIDown(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBaseCommandFieldNumber = 1,
    kLinearLiftCommandFieldNumber = 2,
    kArmCommandFieldNumber = 3,
    kRotateLiftCommandFieldNumber = 4,
    kSetReportFrequencyFieldNumber = 5,
    kSecondaryDeviceCommandFieldNumber = 7,
    kEnableKcpFieldNumber = 8,
    kPlaceholderMessageFieldNumber = 100,
  };
  // .BaseCommand base_command = 1;
  bool has_base_command() const;
  private:
  bool _internal_has_base_command() const;
  public:
  void clear_base_command();
  const ::BaseCommand& base_command() const;
  PROTOBUF_NODISCARD ::BaseCommand* release_base_command();
  ::BaseCommand* mutable_base_command();
  void set_allocated_base_command(::BaseCommand* base_command);
  private:
  const ::BaseCommand& _internal_base_command() const;
  ::BaseCommand* _internal_mutable_base_command();
  public:
  void unsafe_arena_set_allocated_base_command(
      ::BaseCommand* base_command);
  ::BaseCommand* unsafe_arena_release_base_command();

  // .LinearLiftCommand linear_lift_command = 2;
  bool has_linear_lift_command() const;
  private:
  bool _internal_has_linear_lift_command() const;
  public:
  void clear_linear_lift_command();
  const ::LinearLiftCommand& linear_lift_command() const;
  PROTOBUF_NODISCARD ::LinearLiftCommand* release_linear_lift_command();
  ::LinearLiftCommand* mutable_linear_lift_command();
  void set_allocated_linear_lift_command(::LinearLiftCommand* linear_lift_command);
  private:
  const ::LinearLiftCommand& _internal_linear_lift_command() const;
  ::LinearLiftCommand* _internal_mutable_linear_lift_command();
  public:
  void unsafe_arena_set_allocated_linear_lift_command(
      ::LinearLiftCommand* linear_lift_command);
  ::LinearLiftCommand* unsafe_arena_release_linear_lift_command();

  // .ArmCommand arm_command = 3;
  bool has_arm_command() const;
  private:
  bool _internal_has_arm_command() const;
  public:
  void clear_arm_command();
  const ::ArmCommand& arm_command() const;
  PROTOBUF_NODISCARD ::ArmCommand* release_arm_command();
  ::ArmCommand* mutable_arm_command();
  void set_allocated_arm_command(::ArmCommand* arm_command);
  private:
  const ::ArmCommand& _internal_arm_command() const;
  ::ArmCommand* _internal_mutable_arm_command();
  public:
  void unsafe_arena_set_allocated_arm_command(
      ::ArmCommand* arm_command);
  ::ArmCommand* unsafe_arena_release_arm_command();

  // .RotateLiftCommand rotate_lift_command = 4;
  bool has_rotate_lift_command() const;
  private:
  bool _internal_has_rotate_lift_command() const;
  public:
  void clear_rotate_lift_command();
  const ::RotateLiftCommand& rotate_lift_command() const;
  PROTOBUF_NODISCARD ::RotateLiftCommand* release_rotate_lift_command();
  ::RotateLiftCommand* mutable_rotate_lift_command();
  void set_allocated_rotate_lift_command(::RotateLiftCommand* rotate_lift_command);
  private:
  const ::RotateLiftCommand& _internal_rotate_lift_command() const;
  ::RotateLiftCommand* _internal_mutable_rotate_lift_command();
  public:
  void unsafe_arena_set_allocated_rotate_lift_command(
      ::RotateLiftCommand* rotate_lift_command);
  ::RotateLiftCommand* unsafe_arena_release_rotate_lift_command();

  // .ReportFrequency set_report_frequency = 5;
  bool has_set_report_frequency() const;
  private:
  bool _internal_has_set_report_frequency() const;
  public:
  void clear_set_report_frequency();
  ::ReportFrequency set_report_frequency() const;
  void set_set_report_frequency(::ReportFrequency value);
  private:
  ::ReportFrequency _internal_set_report_frequency() const;
  void _internal_set_set_report_frequency(::ReportFrequency value);
  public:

  // .SecondaryDeviceCommand secondary_device_command = 7;
  bool has_secondary_device_command() const;
  private:
  bool _internal_has_secondary_device_command() const;
  public:
  void clear_secondary_device_command();
  const ::SecondaryDeviceCommand& secondary_device_command() const;
  PROTOBUF_NODISCARD ::SecondaryDeviceCommand* release_secondary_device_command();
  ::SecondaryDeviceCommand* mutable_secondary_device_command();
  void set_allocated_secondary_device_command(::SecondaryDeviceCommand* secondary_device_command);
  private:
  const ::SecondaryDeviceCommand& _internal_secondary_device_command() const;
  ::SecondaryDeviceCommand* _internal_mutable_secondary_device_command();
  public:
  void unsafe_arena_set_allocated_secondary_device_command(
      ::SecondaryDeviceCommand* secondary_device_command);
  ::SecondaryDeviceCommand* unsafe_arena_release_secondary_device_command();

  // .EnableKcp enable_kcp = 8;
  bool has_enable_kcp() const;
  private:
  bool _internal_has_enable_kcp() const;
  public:
  void clear_enable_kcp();
  const ::EnableKcp& enable_kcp() const;
  PROTOBUF_NODISCARD ::EnableKcp* release_enable_kcp();
  ::EnableKcp* mutable_enable_kcp();
  void set_allocated_enable_kcp(::EnableKcp* enable_kcp);
  private:
  const ::EnableKcp& _internal_enable_kcp() const;
  ::EnableKcp* _internal_mutable_enable_kcp();
  public:
  void unsafe_arena_set_allocated_enable_kcp(
      ::EnableKcp* enable_kcp);
  ::EnableKcp* unsafe_arena_release_enable_kcp();

  // bool placeholder_message = 100;
  bool has_placeholder_message() const;
  private:
  bool _internal_has_placeholder_message() const;
  public:
  void clear_placeholder_message();
  bool placeholder_message() const;
  void set_placeholder_message(bool value);
  private:
  bool _internal_placeholder_message() const;
  void _internal_set_placeholder_message(bool value);
  public:

  void clear_down();
  DownCase down_case() const;
  // @@protoc_insertion_point(class_scope:APIDown)
 private:
  class _Internal;
  void set_has_base_command();
  void set_has_linear_lift_command();
  void set_has_arm_command();
  void set_has_rotate_lift_command();
  void set_has_set_report_frequency();
  void set_has_secondary_device_command();
  void set_has_enable_kcp();
  void set_has_placeholder_message();

  inline bool has_down() const;
  inline void clear_has_down();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  union DownUnion {
    constexpr DownUnion() : _constinit_{} {}
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
    ::BaseCommand* base_command_;
    ::LinearLiftCommand* linear_lift_command_;
    ::ArmCommand* arm_command_;
    ::RotateLiftCommand* rotate_lift_command_;
    int set_report_frequency_;
    ::SecondaryDeviceCommand* secondary_device_command_;
    ::EnableKcp* enable_kcp_;
    bool placeholder_message_;
  } down_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  uint32_t _oneof_case_[1];

  friend struct ::TableStruct_public_5fapi_5fdown_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// APIDown

// .BaseCommand base_command = 1;
inline bool APIDown::_internal_has_base_command() const {
  return down_case() == kBaseCommand;
}
inline bool APIDown::has_base_command() const {
  return _internal_has_base_command();
}
inline void APIDown::set_has_base_command() {
  _oneof_case_[0] = kBaseCommand;
}
inline ::BaseCommand* APIDown::release_base_command() {
  // @@protoc_insertion_point(field_release:APIDown.base_command)
  if (_internal_has_base_command()) {
    clear_has_down();
      ::BaseCommand* temp = down_.base_command_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    down_.base_command_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::BaseCommand& APIDown::_internal_base_command() const {
  return _internal_has_base_command()
      ? *down_.base_command_
      : reinterpret_cast< ::BaseCommand&>(::_BaseCommand_default_instance_);
}
inline const ::BaseCommand& APIDown::base_command() const {
  // @@protoc_insertion_point(field_get:APIDown.base_command)
  return _internal_base_command();
}
inline ::BaseCommand* APIDown::unsafe_arena_release_base_command() {
  // @@protoc_insertion_point(field_unsafe_arena_release:APIDown.base_command)
  if (_internal_has_base_command()) {
    clear_has_down();
    ::BaseCommand* temp = down_.base_command_;
    down_.base_command_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void APIDown::unsafe_arena_set_allocated_base_command(::BaseCommand* base_command) {
  clear_down();
  if (base_command) {
    set_has_base_command();
    down_.base_command_ = base_command;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:APIDown.base_command)
}
inline ::BaseCommand* APIDown::_internal_mutable_base_command() {
  if (!_internal_has_base_command()) {
    clear_down();
    set_has_base_command();
    down_.base_command_ = CreateMaybeMessage< ::BaseCommand >(GetArenaForAllocation());
  }
  return down_.base_command_;
}
inline ::BaseCommand* APIDown::mutable_base_command() {
  ::BaseCommand* _msg = _internal_mutable_base_command();
  // @@protoc_insertion_point(field_mutable:APIDown.base_command)
  return _msg;
}

// .LinearLiftCommand linear_lift_command = 2;
inline bool APIDown::_internal_has_linear_lift_command() const {
  return down_case() == kLinearLiftCommand;
}
inline bool APIDown::has_linear_lift_command() const {
  return _internal_has_linear_lift_command();
}
inline void APIDown::set_has_linear_lift_command() {
  _oneof_case_[0] = kLinearLiftCommand;
}
inline ::LinearLiftCommand* APIDown::release_linear_lift_command() {
  // @@protoc_insertion_point(field_release:APIDown.linear_lift_command)
  if (_internal_has_linear_lift_command()) {
    clear_has_down();
      ::LinearLiftCommand* temp = down_.linear_lift_command_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    down_.linear_lift_command_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::LinearLiftCommand& APIDown::_internal_linear_lift_command() const {
  return _internal_has_linear_lift_command()
      ? *down_.linear_lift_command_
      : reinterpret_cast< ::LinearLiftCommand&>(::_LinearLiftCommand_default_instance_);
}
inline const ::LinearLiftCommand& APIDown::linear_lift_command() const {
  // @@protoc_insertion_point(field_get:APIDown.linear_lift_command)
  return _internal_linear_lift_command();
}
inline ::LinearLiftCommand* APIDown::unsafe_arena_release_linear_lift_command() {
  // @@protoc_insertion_point(field_unsafe_arena_release:APIDown.linear_lift_command)
  if (_internal_has_linear_lift_command()) {
    clear_has_down();
    ::LinearLiftCommand* temp = down_.linear_lift_command_;
    down_.linear_lift_command_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void APIDown::unsafe_arena_set_allocated_linear_lift_command(::LinearLiftCommand* linear_lift_command) {
  clear_down();
  if (linear_lift_command) {
    set_has_linear_lift_command();
    down_.linear_lift_command_ = linear_lift_command;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:APIDown.linear_lift_command)
}
inline ::LinearLiftCommand* APIDown::_internal_mutable_linear_lift_command() {
  if (!_internal_has_linear_lift_command()) {
    clear_down();
    set_has_linear_lift_command();
    down_.linear_lift_command_ = CreateMaybeMessage< ::LinearLiftCommand >(GetArenaForAllocation());
  }
  return down_.linear_lift_command_;
}
inline ::LinearLiftCommand* APIDown::mutable_linear_lift_command() {
  ::LinearLiftCommand* _msg = _internal_mutable_linear_lift_command();
  // @@protoc_insertion_point(field_mutable:APIDown.linear_lift_command)
  return _msg;
}

// .ArmCommand arm_command = 3;
inline bool APIDown::_internal_has_arm_command() const {
  return down_case() == kArmCommand;
}
inline bool APIDown::has_arm_command() const {
  return _internal_has_arm_command();
}
inline void APIDown::set_has_arm_command() {
  _oneof_case_[0] = kArmCommand;
}
inline ::ArmCommand* APIDown::release_arm_command() {
  // @@protoc_insertion_point(field_release:APIDown.arm_command)
  if (_internal_has_arm_command()) {
    clear_has_down();
      ::ArmCommand* temp = down_.arm_command_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    down_.arm_command_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::ArmCommand& APIDown::_internal_arm_command() const {
  return _internal_has_arm_command()
      ? *down_.arm_command_
      : reinterpret_cast< ::ArmCommand&>(::_ArmCommand_default_instance_);
}
inline const ::ArmCommand& APIDown::arm_command() const {
  // @@protoc_insertion_point(field_get:APIDown.arm_command)
  return _internal_arm_command();
}
inline ::ArmCommand* APIDown::unsafe_arena_release_arm_command() {
  // @@protoc_insertion_point(field_unsafe_arena_release:APIDown.arm_command)
  if (_internal_has_arm_command()) {
    clear_has_down();
    ::ArmCommand* temp = down_.arm_command_;
    down_.arm_command_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void APIDown::unsafe_arena_set_allocated_arm_command(::ArmCommand* arm_command) {
  clear_down();
  if (arm_command) {
    set_has_arm_command();
    down_.arm_command_ = arm_command;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:APIDown.arm_command)
}
inline ::ArmCommand* APIDown::_internal_mutable_arm_command() {
  if (!_internal_has_arm_command()) {
    clear_down();
    set_has_arm_command();
    down_.arm_command_ = CreateMaybeMessage< ::ArmCommand >(GetArenaForAllocation());
  }
  return down_.arm_command_;
}
inline ::ArmCommand* APIDown::mutable_arm_command() {
  ::ArmCommand* _msg = _internal_mutable_arm_command();
  // @@protoc_insertion_point(field_mutable:APIDown.arm_command)
  return _msg;
}

// .RotateLiftCommand rotate_lift_command = 4;
inline bool APIDown::_internal_has_rotate_lift_command() const {
  return down_case() == kRotateLiftCommand;
}
inline bool APIDown::has_rotate_lift_command() const {
  return _internal_has_rotate_lift_command();
}
inline void APIDown::set_has_rotate_lift_command() {
  _oneof_case_[0] = kRotateLiftCommand;
}
inline ::RotateLiftCommand* APIDown::release_rotate_lift_command() {
  // @@protoc_insertion_point(field_release:APIDown.rotate_lift_command)
  if (_internal_has_rotate_lift_command()) {
    clear_has_down();
      ::RotateLiftCommand* temp = down_.rotate_lift_command_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    down_.rotate_lift_command_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::RotateLiftCommand& APIDown::_internal_rotate_lift_command() const {
  return _internal_has_rotate_lift_command()
      ? *down_.rotate_lift_command_
      : reinterpret_cast< ::RotateLiftCommand&>(::_RotateLiftCommand_default_instance_);
}
inline const ::RotateLiftCommand& APIDown::rotate_lift_command() const {
  // @@protoc_insertion_point(field_get:APIDown.rotate_lift_command)
  return _internal_rotate_lift_command();
}
inline ::RotateLiftCommand* APIDown::unsafe_arena_release_rotate_lift_command() {
  // @@protoc_insertion_point(field_unsafe_arena_release:APIDown.rotate_lift_command)
  if (_internal_has_rotate_lift_command()) {
    clear_has_down();
    ::RotateLiftCommand* temp = down_.rotate_lift_command_;
    down_.rotate_lift_command_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void APIDown::unsafe_arena_set_allocated_rotate_lift_command(::RotateLiftCommand* rotate_lift_command) {
  clear_down();
  if (rotate_lift_command) {
    set_has_rotate_lift_command();
    down_.rotate_lift_command_ = rotate_lift_command;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:APIDown.rotate_lift_command)
}
inline ::RotateLiftCommand* APIDown::_internal_mutable_rotate_lift_command() {
  if (!_internal_has_rotate_lift_command()) {
    clear_down();
    set_has_rotate_lift_command();
    down_.rotate_lift_command_ = CreateMaybeMessage< ::RotateLiftCommand >(GetArenaForAllocation());
  }
  return down_.rotate_lift_command_;
}
inline ::RotateLiftCommand* APIDown::mutable_rotate_lift_command() {
  ::RotateLiftCommand* _msg = _internal_mutable_rotate_lift_command();
  // @@protoc_insertion_point(field_mutable:APIDown.rotate_lift_command)
  return _msg;
}

// .ReportFrequency set_report_frequency = 5;
inline bool APIDown::_internal_has_set_report_frequency() const {
  return down_case() == kSetReportFrequency;
}
inline bool APIDown::has_set_report_frequency() const {
  return _internal_has_set_report_frequency();
}
inline void APIDown::set_has_set_report_frequency() {
  _oneof_case_[0] = kSetReportFrequency;
}
inline void APIDown::clear_set_report_frequency() {
  if (_internal_has_set_report_frequency()) {
    down_.set_report_frequency_ = 0;
    clear_has_down();
  }
}
inline ::ReportFrequency APIDown::_internal_set_report_frequency() const {
  if (_internal_has_set_report_frequency()) {
    return static_cast< ::ReportFrequency >(down_.set_report_frequency_);
  }
  return static_cast< ::ReportFrequency >(0);
}
inline ::ReportFrequency APIDown::set_report_frequency() const {
  // @@protoc_insertion_point(field_get:APIDown.set_report_frequency)
  return _internal_set_report_frequency();
}
inline void APIDown::_internal_set_set_report_frequency(::ReportFrequency value) {
  if (!_internal_has_set_report_frequency()) {
    clear_down();
    set_has_set_report_frequency();
  }
  down_.set_report_frequency_ = value;
}
inline void APIDown::set_set_report_frequency(::ReportFrequency value) {
  _internal_set_set_report_frequency(value);
  // @@protoc_insertion_point(field_set:APIDown.set_report_frequency)
}

// .SecondaryDeviceCommand secondary_device_command = 7;
inline bool APIDown::_internal_has_secondary_device_command() const {
  return down_case() == kSecondaryDeviceCommand;
}
inline bool APIDown::has_secondary_device_command() const {
  return _internal_has_secondary_device_command();
}
inline void APIDown::set_has_secondary_device_command() {
  _oneof_case_[0] = kSecondaryDeviceCommand;
}
inline ::SecondaryDeviceCommand* APIDown::release_secondary_device_command() {
  // @@protoc_insertion_point(field_release:APIDown.secondary_device_command)
  if (_internal_has_secondary_device_command()) {
    clear_has_down();
      ::SecondaryDeviceCommand* temp = down_.secondary_device_command_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    down_.secondary_device_command_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::SecondaryDeviceCommand& APIDown::_internal_secondary_device_command() const {
  return _internal_has_secondary_device_command()
      ? *down_.secondary_device_command_
      : reinterpret_cast< ::SecondaryDeviceCommand&>(::_SecondaryDeviceCommand_default_instance_);
}
inline const ::SecondaryDeviceCommand& APIDown::secondary_device_command() const {
  // @@protoc_insertion_point(field_get:APIDown.secondary_device_command)
  return _internal_secondary_device_command();
}
inline ::SecondaryDeviceCommand* APIDown::unsafe_arena_release_secondary_device_command() {
  // @@protoc_insertion_point(field_unsafe_arena_release:APIDown.secondary_device_command)
  if (_internal_has_secondary_device_command()) {
    clear_has_down();
    ::SecondaryDeviceCommand* temp = down_.secondary_device_command_;
    down_.secondary_device_command_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void APIDown::unsafe_arena_set_allocated_secondary_device_command(::SecondaryDeviceCommand* secondary_device_command) {
  clear_down();
  if (secondary_device_command) {
    set_has_secondary_device_command();
    down_.secondary_device_command_ = secondary_device_command;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:APIDown.secondary_device_command)
}
inline ::SecondaryDeviceCommand* APIDown::_internal_mutable_secondary_device_command() {
  if (!_internal_has_secondary_device_command()) {
    clear_down();
    set_has_secondary_device_command();
    down_.secondary_device_command_ = CreateMaybeMessage< ::SecondaryDeviceCommand >(GetArenaForAllocation());
  }
  return down_.secondary_device_command_;
}
inline ::SecondaryDeviceCommand* APIDown::mutable_secondary_device_command() {
  ::SecondaryDeviceCommand* _msg = _internal_mutable_secondary_device_command();
  // @@protoc_insertion_point(field_mutable:APIDown.secondary_device_command)
  return _msg;
}

// .EnableKcp enable_kcp = 8;
inline bool APIDown::_internal_has_enable_kcp() const {
  return down_case() == kEnableKcp;
}
inline bool APIDown::has_enable_kcp() const {
  return _internal_has_enable_kcp();
}
inline void APIDown::set_has_enable_kcp() {
  _oneof_case_[0] = kEnableKcp;
}
inline ::EnableKcp* APIDown::release_enable_kcp() {
  // @@protoc_insertion_point(field_release:APIDown.enable_kcp)
  if (_internal_has_enable_kcp()) {
    clear_has_down();
      ::EnableKcp* temp = down_.enable_kcp_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    down_.enable_kcp_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::EnableKcp& APIDown::_internal_enable_kcp() const {
  return _internal_has_enable_kcp()
      ? *down_.enable_kcp_
      : reinterpret_cast< ::EnableKcp&>(::_EnableKcp_default_instance_);
}
inline const ::EnableKcp& APIDown::enable_kcp() const {
  // @@protoc_insertion_point(field_get:APIDown.enable_kcp)
  return _internal_enable_kcp();
}
inline ::EnableKcp* APIDown::unsafe_arena_release_enable_kcp() {
  // @@protoc_insertion_point(field_unsafe_arena_release:APIDown.enable_kcp)
  if (_internal_has_enable_kcp()) {
    clear_has_down();
    ::EnableKcp* temp = down_.enable_kcp_;
    down_.enable_kcp_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void APIDown::unsafe_arena_set_allocated_enable_kcp(::EnableKcp* enable_kcp) {
  clear_down();
  if (enable_kcp) {
    set_has_enable_kcp();
    down_.enable_kcp_ = enable_kcp;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:APIDown.enable_kcp)
}
inline ::EnableKcp* APIDown::_internal_mutable_enable_kcp() {
  if (!_internal_has_enable_kcp()) {
    clear_down();
    set_has_enable_kcp();
    down_.enable_kcp_ = CreateMaybeMessage< ::EnableKcp >(GetArenaForAllocation());
  }
  return down_.enable_kcp_;
}
inline ::EnableKcp* APIDown::mutable_enable_kcp() {
  ::EnableKcp* _msg = _internal_mutable_enable_kcp();
  // @@protoc_insertion_point(field_mutable:APIDown.enable_kcp)
  return _msg;
}

// bool placeholder_message = 100;
inline bool APIDown::_internal_has_placeholder_message() const {
  return down_case() == kPlaceholderMessage;
}
inline bool APIDown::has_placeholder_message() const {
  return _internal_has_placeholder_message();
}
inline void APIDown::set_has_placeholder_message() {
  _oneof_case_[0] = kPlaceholderMessage;
}
inline void APIDown::clear_placeholder_message() {
  if (_internal_has_placeholder_message()) {
    down_.placeholder_message_ = false;
    clear_has_down();
  }
}
inline bool APIDown::_internal_placeholder_message() const {
  if (_internal_has_placeholder_message()) {
    return down_.placeholder_message_;
  }
  return false;
}
inline void APIDown::_internal_set_placeholder_message(bool value) {
  if (!_internal_has_placeholder_message()) {
    clear_down();
    set_has_placeholder_message();
  }
  down_.placeholder_message_ = value;
}
inline bool APIDown::placeholder_message() const {
  // @@protoc_insertion_point(field_get:APIDown.placeholder_message)
  return _internal_placeholder_message();
}
inline void APIDown::set_placeholder_message(bool value) {
  _internal_set_placeholder_message(value);
  // @@protoc_insertion_point(field_set:APIDown.placeholder_message)
}

inline bool APIDown::has_down() const {
  return down_case() != DOWN_NOT_SET;
}
inline void APIDown::clear_has_down() {
  _oneof_case_[0] = DOWN_NOT_SET;
}
inline APIDown::DownCase APIDown::down_case() const {
  return APIDown::DownCase(_oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_public_5fapi_5fdown_2eproto
