// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: public_api_up.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_public_5fapi_5fup_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_public_5fapi_5fup_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "public_api_types.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_public_5fapi_5fup_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_public_5fapi_5fup_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_public_5fapi_5fup_2eproto;
class APIUp;
struct APIUpDefaultTypeInternal;
extern APIUpDefaultTypeInternal _APIUp_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::APIUp* Arena::CreateMaybeMessage<::APIUp>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class APIUp final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:APIUp) */ {
 public:
  inline APIUp() : APIUp(nullptr) {}
  ~APIUp() override;
  explicit constexpr APIUp(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  APIUp(const APIUp& from);
  APIUp(APIUp&& from) noexcept
    : APIUp() {
    *this = ::std::move(from);
  }

  inline APIUp& operator=(const APIUp& from) {
    CopyFrom(from);
    return *this;
  }
  inline APIUp& operator=(APIUp&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const APIUp& default_instance() {
    return *internal_default_instance();
  }
  enum StatusCase {
    kBaseStatus = 2,
    kLinearLiftStatus = 3,
    kRotateLiftStatus = 5,
    kArmStatus = 4,
    STATUS_NOT_SET = 0,
  };

  static inline const APIUp* internal_default_instance() {
    return reinterpret_cast<const APIUp*>(
               &_APIUp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(APIUp& a, APIUp& b) {
    a.Swap(&b);
  }
  inline void Swap(APIUp* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(APIUp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  APIUp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<APIUp>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const APIUp& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const APIUp& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(APIUp* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "APIUp";
  }
  protected:
  explicit APIUp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSecondaryDeviceStatusFieldNumber = 16,
    kLogFieldNumber = 14,
    kKcpServerStatusFieldNumber = 19,
    kRobotTypeFieldNumber = 1,
    kReportFrequencyFieldNumber = 12,
    kProtocolMinorVersionFieldNumber = 18,
    kSessionIdFieldNumber = 15,
    kProtocolMajorVersionFieldNumber = 17,
    kBaseStatusFieldNumber = 2,
    kLinearLiftStatusFieldNumber = 3,
    kRotateLiftStatusFieldNumber = 5,
    kArmStatusFieldNumber = 4,
  };
  // repeated .SecondaryDeviceStatus secondary_device_status = 16;
  int secondary_device_status_size() const;
  private:
  int _internal_secondary_device_status_size() const;
  public:
  void clear_secondary_device_status();
  ::SecondaryDeviceStatus* mutable_secondary_device_status(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::SecondaryDeviceStatus >*
      mutable_secondary_device_status();
  private:
  const ::SecondaryDeviceStatus& _internal_secondary_device_status(int index) const;
  ::SecondaryDeviceStatus* _internal_add_secondary_device_status();
  public:
  const ::SecondaryDeviceStatus& secondary_device_status(int index) const;
  ::SecondaryDeviceStatus* add_secondary_device_status();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::SecondaryDeviceStatus >&
      secondary_device_status() const;

  // optional string log = 14;
  bool has_log() const;
  private:
  bool _internal_has_log() const;
  public:
  void clear_log();
  const std::string& log() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_log(ArgT0&& arg0, ArgT... args);
  std::string* mutable_log();
  PROTOBUF_NODISCARD std::string* release_log();
  void set_allocated_log(std::string* log);
  private:
  const std::string& _internal_log() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_log(const std::string& value);
  std::string* _internal_mutable_log();
  public:

  // optional .KcpServerStatus kcp_server_status = 19;
  bool has_kcp_server_status() const;
  private:
  bool _internal_has_kcp_server_status() const;
  public:
  void clear_kcp_server_status();
  const ::KcpServerStatus& kcp_server_status() const;
  PROTOBUF_NODISCARD ::KcpServerStatus* release_kcp_server_status();
  ::KcpServerStatus* mutable_kcp_server_status();
  void set_allocated_kcp_server_status(::KcpServerStatus* kcp_server_status);
  private:
  const ::KcpServerStatus& _internal_kcp_server_status() const;
  ::KcpServerStatus* _internal_mutable_kcp_server_status();
  public:
  void unsafe_arena_set_allocated_kcp_server_status(
      ::KcpServerStatus* kcp_server_status);
  ::KcpServerStatus* unsafe_arena_release_kcp_server_status();

  // .RobotType robot_type = 1;
  void clear_robot_type();
  ::RobotType robot_type() const;
  void set_robot_type(::RobotType value);
  private:
  ::RobotType _internal_robot_type() const;
  void _internal_set_robot_type(::RobotType value);
  public:

  // .ReportFrequency report_frequency = 12;
  void clear_report_frequency();
  ::ReportFrequency report_frequency() const;
  void set_report_frequency(::ReportFrequency value);
  private:
  ::ReportFrequency _internal_report_frequency() const;
  void _internal_set_report_frequency(::ReportFrequency value);
  public:

  // uint32 protocol_minor_version = 18;
  void clear_protocol_minor_version();
  uint32_t protocol_minor_version() const;
  void set_protocol_minor_version(uint32_t value);
  private:
  uint32_t _internal_protocol_minor_version() const;
  void _internal_set_protocol_minor_version(uint32_t value);
  public:

  // uint32 session_id = 15;
  void clear_session_id();
  uint32_t session_id() const;
  void set_session_id(uint32_t value);
  private:
  uint32_t _internal_session_id() const;
  void _internal_set_session_id(uint32_t value);
  public:

  // uint32 protocol_major_version = 17;
  void clear_protocol_major_version();
  uint32_t protocol_major_version() const;
  void set_protocol_major_version(uint32_t value);
  private:
  uint32_t _internal_protocol_major_version() const;
  void _internal_set_protocol_major_version(uint32_t value);
  public:

  // .BaseStatus base_status = 2;
  bool has_base_status() const;
  private:
  bool _internal_has_base_status() const;
  public:
  void clear_base_status();
  const ::BaseStatus& base_status() const;
  PROTOBUF_NODISCARD ::BaseStatus* release_base_status();
  ::BaseStatus* mutable_base_status();
  void set_allocated_base_status(::BaseStatus* base_status);
  private:
  const ::BaseStatus& _internal_base_status() const;
  ::BaseStatus* _internal_mutable_base_status();
  public:
  void unsafe_arena_set_allocated_base_status(
      ::BaseStatus* base_status);
  ::BaseStatus* unsafe_arena_release_base_status();

  // .LinearLiftStatus linear_lift_status = 3;
  bool has_linear_lift_status() const;
  private:
  bool _internal_has_linear_lift_status() const;
  public:
  void clear_linear_lift_status();
  const ::LinearLiftStatus& linear_lift_status() const;
  PROTOBUF_NODISCARD ::LinearLiftStatus* release_linear_lift_status();
  ::LinearLiftStatus* mutable_linear_lift_status();
  void set_allocated_linear_lift_status(::LinearLiftStatus* linear_lift_status);
  private:
  const ::LinearLiftStatus& _internal_linear_lift_status() const;
  ::LinearLiftStatus* _internal_mutable_linear_lift_status();
  public:
  void unsafe_arena_set_allocated_linear_lift_status(
      ::LinearLiftStatus* linear_lift_status);
  ::LinearLiftStatus* unsafe_arena_release_linear_lift_status();

  // .RotateLiftStatus rotate_lift_status = 5;
  bool has_rotate_lift_status() const;
  private:
  bool _internal_has_rotate_lift_status() const;
  public:
  void clear_rotate_lift_status();
  const ::RotateLiftStatus& rotate_lift_status() const;
  PROTOBUF_NODISCARD ::RotateLiftStatus* release_rotate_lift_status();
  ::RotateLiftStatus* mutable_rotate_lift_status();
  void set_allocated_rotate_lift_status(::RotateLiftStatus* rotate_lift_status);
  private:
  const ::RotateLiftStatus& _internal_rotate_lift_status() const;
  ::RotateLiftStatus* _internal_mutable_rotate_lift_status();
  public:
  void unsafe_arena_set_allocated_rotate_lift_status(
      ::RotateLiftStatus* rotate_lift_status);
  ::RotateLiftStatus* unsafe_arena_release_rotate_lift_status();

  // .ArmStatus arm_status = 4;
  bool has_arm_status() const;
  private:
  bool _internal_has_arm_status() const;
  public:
  void clear_arm_status();
  const ::ArmStatus& arm_status() const;
  PROTOBUF_NODISCARD ::ArmStatus* release_arm_status();
  ::ArmStatus* mutable_arm_status();
  void set_allocated_arm_status(::ArmStatus* arm_status);
  private:
  const ::ArmStatus& _internal_arm_status() const;
  ::ArmStatus* _internal_mutable_arm_status();
  public:
  void unsafe_arena_set_allocated_arm_status(
      ::ArmStatus* arm_status);
  ::ArmStatus* unsafe_arena_release_arm_status();

  void clear_status();
  StatusCase status_case() const;
  // @@protoc_insertion_point(class_scope:APIUp)
 private:
  class _Internal;
  void set_has_base_status();
  void set_has_linear_lift_status();
  void set_has_rotate_lift_status();
  void set_has_arm_status();

  inline bool has_status() const;
  inline void clear_has_status();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::SecondaryDeviceStatus > secondary_device_status_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr log_;
  ::KcpServerStatus* kcp_server_status_;
  int robot_type_;
  int report_frequency_;
  uint32_t protocol_minor_version_;
  uint32_t session_id_;
  uint32_t protocol_major_version_;
  union StatusUnion {
    constexpr StatusUnion() : _constinit_{} {}
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
    ::BaseStatus* base_status_;
    ::LinearLiftStatus* linear_lift_status_;
    ::RotateLiftStatus* rotate_lift_status_;
    ::ArmStatus* arm_status_;
  } status_;
  uint32_t _oneof_case_[1];

  friend struct ::TableStruct_public_5fapi_5fup_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// APIUp

// .RobotType robot_type = 1;
inline void APIUp::clear_robot_type() {
  robot_type_ = 0;
}
inline ::RobotType APIUp::_internal_robot_type() const {
  return static_cast< ::RobotType >(robot_type_);
}
inline ::RobotType APIUp::robot_type() const {
  // @@protoc_insertion_point(field_get:APIUp.robot_type)
  return _internal_robot_type();
}
inline void APIUp::_internal_set_robot_type(::RobotType value) {
  
  robot_type_ = value;
}
inline void APIUp::set_robot_type(::RobotType value) {
  _internal_set_robot_type(value);
  // @@protoc_insertion_point(field_set:APIUp.robot_type)
}

// uint32 protocol_major_version = 17;
inline void APIUp::clear_protocol_major_version() {
  protocol_major_version_ = 0u;
}
inline uint32_t APIUp::_internal_protocol_major_version() const {
  return protocol_major_version_;
}
inline uint32_t APIUp::protocol_major_version() const {
  // @@protoc_insertion_point(field_get:APIUp.protocol_major_version)
  return _internal_protocol_major_version();
}
inline void APIUp::_internal_set_protocol_major_version(uint32_t value) {
  
  protocol_major_version_ = value;
}
inline void APIUp::set_protocol_major_version(uint32_t value) {
  _internal_set_protocol_major_version(value);
  // @@protoc_insertion_point(field_set:APIUp.protocol_major_version)
}

// uint32 protocol_minor_version = 18;
inline void APIUp::clear_protocol_minor_version() {
  protocol_minor_version_ = 0u;
}
inline uint32_t APIUp::_internal_protocol_minor_version() const {
  return protocol_minor_version_;
}
inline uint32_t APIUp::protocol_minor_version() const {
  // @@protoc_insertion_point(field_get:APIUp.protocol_minor_version)
  return _internal_protocol_minor_version();
}
inline void APIUp::_internal_set_protocol_minor_version(uint32_t value) {
  
  protocol_minor_version_ = value;
}
inline void APIUp::set_protocol_minor_version(uint32_t value) {
  _internal_set_protocol_minor_version(value);
  // @@protoc_insertion_point(field_set:APIUp.protocol_minor_version)
}

// .BaseStatus base_status = 2;
inline bool APIUp::_internal_has_base_status() const {
  return status_case() == kBaseStatus;
}
inline bool APIUp::has_base_status() const {
  return _internal_has_base_status();
}
inline void APIUp::set_has_base_status() {
  _oneof_case_[0] = kBaseStatus;
}
inline ::BaseStatus* APIUp::release_base_status() {
  // @@protoc_insertion_point(field_release:APIUp.base_status)
  if (_internal_has_base_status()) {
    clear_has_status();
      ::BaseStatus* temp = status_.base_status_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    status_.base_status_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::BaseStatus& APIUp::_internal_base_status() const {
  return _internal_has_base_status()
      ? *status_.base_status_
      : reinterpret_cast< ::BaseStatus&>(::_BaseStatus_default_instance_);
}
inline const ::BaseStatus& APIUp::base_status() const {
  // @@protoc_insertion_point(field_get:APIUp.base_status)
  return _internal_base_status();
}
inline ::BaseStatus* APIUp::unsafe_arena_release_base_status() {
  // @@protoc_insertion_point(field_unsafe_arena_release:APIUp.base_status)
  if (_internal_has_base_status()) {
    clear_has_status();
    ::BaseStatus* temp = status_.base_status_;
    status_.base_status_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void APIUp::unsafe_arena_set_allocated_base_status(::BaseStatus* base_status) {
  clear_status();
  if (base_status) {
    set_has_base_status();
    status_.base_status_ = base_status;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:APIUp.base_status)
}
inline ::BaseStatus* APIUp::_internal_mutable_base_status() {
  if (!_internal_has_base_status()) {
    clear_status();
    set_has_base_status();
    status_.base_status_ = CreateMaybeMessage< ::BaseStatus >(GetArenaForAllocation());
  }
  return status_.base_status_;
}
inline ::BaseStatus* APIUp::mutable_base_status() {
  ::BaseStatus* _msg = _internal_mutable_base_status();
  // @@protoc_insertion_point(field_mutable:APIUp.base_status)
  return _msg;
}

// .LinearLiftStatus linear_lift_status = 3;
inline bool APIUp::_internal_has_linear_lift_status() const {
  return status_case() == kLinearLiftStatus;
}
inline bool APIUp::has_linear_lift_status() const {
  return _internal_has_linear_lift_status();
}
inline void APIUp::set_has_linear_lift_status() {
  _oneof_case_[0] = kLinearLiftStatus;
}
inline ::LinearLiftStatus* APIUp::release_linear_lift_status() {
  // @@protoc_insertion_point(field_release:APIUp.linear_lift_status)
  if (_internal_has_linear_lift_status()) {
    clear_has_status();
      ::LinearLiftStatus* temp = status_.linear_lift_status_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    status_.linear_lift_status_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::LinearLiftStatus& APIUp::_internal_linear_lift_status() const {
  return _internal_has_linear_lift_status()
      ? *status_.linear_lift_status_
      : reinterpret_cast< ::LinearLiftStatus&>(::_LinearLiftStatus_default_instance_);
}
inline const ::LinearLiftStatus& APIUp::linear_lift_status() const {
  // @@protoc_insertion_point(field_get:APIUp.linear_lift_status)
  return _internal_linear_lift_status();
}
inline ::LinearLiftStatus* APIUp::unsafe_arena_release_linear_lift_status() {
  // @@protoc_insertion_point(field_unsafe_arena_release:APIUp.linear_lift_status)
  if (_internal_has_linear_lift_status()) {
    clear_has_status();
    ::LinearLiftStatus* temp = status_.linear_lift_status_;
    status_.linear_lift_status_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void APIUp::unsafe_arena_set_allocated_linear_lift_status(::LinearLiftStatus* linear_lift_status) {
  clear_status();
  if (linear_lift_status) {
    set_has_linear_lift_status();
    status_.linear_lift_status_ = linear_lift_status;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:APIUp.linear_lift_status)
}
inline ::LinearLiftStatus* APIUp::_internal_mutable_linear_lift_status() {
  if (!_internal_has_linear_lift_status()) {
    clear_status();
    set_has_linear_lift_status();
    status_.linear_lift_status_ = CreateMaybeMessage< ::LinearLiftStatus >(GetArenaForAllocation());
  }
  return status_.linear_lift_status_;
}
inline ::LinearLiftStatus* APIUp::mutable_linear_lift_status() {
  ::LinearLiftStatus* _msg = _internal_mutable_linear_lift_status();
  // @@protoc_insertion_point(field_mutable:APIUp.linear_lift_status)
  return _msg;
}

// .RotateLiftStatus rotate_lift_status = 5;
inline bool APIUp::_internal_has_rotate_lift_status() const {
  return status_case() == kRotateLiftStatus;
}
inline bool APIUp::has_rotate_lift_status() const {
  return _internal_has_rotate_lift_status();
}
inline void APIUp::set_has_rotate_lift_status() {
  _oneof_case_[0] = kRotateLiftStatus;
}
inline ::RotateLiftStatus* APIUp::release_rotate_lift_status() {
  // @@protoc_insertion_point(field_release:APIUp.rotate_lift_status)
  if (_internal_has_rotate_lift_status()) {
    clear_has_status();
      ::RotateLiftStatus* temp = status_.rotate_lift_status_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    status_.rotate_lift_status_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::RotateLiftStatus& APIUp::_internal_rotate_lift_status() const {
  return _internal_has_rotate_lift_status()
      ? *status_.rotate_lift_status_
      : reinterpret_cast< ::RotateLiftStatus&>(::_RotateLiftStatus_default_instance_);
}
inline const ::RotateLiftStatus& APIUp::rotate_lift_status() const {
  // @@protoc_insertion_point(field_get:APIUp.rotate_lift_status)
  return _internal_rotate_lift_status();
}
inline ::RotateLiftStatus* APIUp::unsafe_arena_release_rotate_lift_status() {
  // @@protoc_insertion_point(field_unsafe_arena_release:APIUp.rotate_lift_status)
  if (_internal_has_rotate_lift_status()) {
    clear_has_status();
    ::RotateLiftStatus* temp = status_.rotate_lift_status_;
    status_.rotate_lift_status_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void APIUp::unsafe_arena_set_allocated_rotate_lift_status(::RotateLiftStatus* rotate_lift_status) {
  clear_status();
  if (rotate_lift_status) {
    set_has_rotate_lift_status();
    status_.rotate_lift_status_ = rotate_lift_status;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:APIUp.rotate_lift_status)
}
inline ::RotateLiftStatus* APIUp::_internal_mutable_rotate_lift_status() {
  if (!_internal_has_rotate_lift_status()) {
    clear_status();
    set_has_rotate_lift_status();
    status_.rotate_lift_status_ = CreateMaybeMessage< ::RotateLiftStatus >(GetArenaForAllocation());
  }
  return status_.rotate_lift_status_;
}
inline ::RotateLiftStatus* APIUp::mutable_rotate_lift_status() {
  ::RotateLiftStatus* _msg = _internal_mutable_rotate_lift_status();
  // @@protoc_insertion_point(field_mutable:APIUp.rotate_lift_status)
  return _msg;
}

// .ArmStatus arm_status = 4;
inline bool APIUp::_internal_has_arm_status() const {
  return status_case() == kArmStatus;
}
inline bool APIUp::has_arm_status() const {
  return _internal_has_arm_status();
}
inline void APIUp::set_has_arm_status() {
  _oneof_case_[0] = kArmStatus;
}
inline ::ArmStatus* APIUp::release_arm_status() {
  // @@protoc_insertion_point(field_release:APIUp.arm_status)
  if (_internal_has_arm_status()) {
    clear_has_status();
      ::ArmStatus* temp = status_.arm_status_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    status_.arm_status_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::ArmStatus& APIUp::_internal_arm_status() const {
  return _internal_has_arm_status()
      ? *status_.arm_status_
      : reinterpret_cast< ::ArmStatus&>(::_ArmStatus_default_instance_);
}
inline const ::ArmStatus& APIUp::arm_status() const {
  // @@protoc_insertion_point(field_get:APIUp.arm_status)
  return _internal_arm_status();
}
inline ::ArmStatus* APIUp::unsafe_arena_release_arm_status() {
  // @@protoc_insertion_point(field_unsafe_arena_release:APIUp.arm_status)
  if (_internal_has_arm_status()) {
    clear_has_status();
    ::ArmStatus* temp = status_.arm_status_;
    status_.arm_status_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void APIUp::unsafe_arena_set_allocated_arm_status(::ArmStatus* arm_status) {
  clear_status();
  if (arm_status) {
    set_has_arm_status();
    status_.arm_status_ = arm_status;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:APIUp.arm_status)
}
inline ::ArmStatus* APIUp::_internal_mutable_arm_status() {
  if (!_internal_has_arm_status()) {
    clear_status();
    set_has_arm_status();
    status_.arm_status_ = CreateMaybeMessage< ::ArmStatus >(GetArenaForAllocation());
  }
  return status_.arm_status_;
}
inline ::ArmStatus* APIUp::mutable_arm_status() {
  ::ArmStatus* _msg = _internal_mutable_arm_status();
  // @@protoc_insertion_point(field_mutable:APIUp.arm_status)
  return _msg;
}

// repeated .SecondaryDeviceStatus secondary_device_status = 16;
inline int APIUp::_internal_secondary_device_status_size() const {
  return secondary_device_status_.size();
}
inline int APIUp::secondary_device_status_size() const {
  return _internal_secondary_device_status_size();
}
inline ::SecondaryDeviceStatus* APIUp::mutable_secondary_device_status(int index) {
  // @@protoc_insertion_point(field_mutable:APIUp.secondary_device_status)
  return secondary_device_status_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::SecondaryDeviceStatus >*
APIUp::mutable_secondary_device_status() {
  // @@protoc_insertion_point(field_mutable_list:APIUp.secondary_device_status)
  return &secondary_device_status_;
}
inline const ::SecondaryDeviceStatus& APIUp::_internal_secondary_device_status(int index) const {
  return secondary_device_status_.Get(index);
}
inline const ::SecondaryDeviceStatus& APIUp::secondary_device_status(int index) const {
  // @@protoc_insertion_point(field_get:APIUp.secondary_device_status)
  return _internal_secondary_device_status(index);
}
inline ::SecondaryDeviceStatus* APIUp::_internal_add_secondary_device_status() {
  return secondary_device_status_.Add();
}
inline ::SecondaryDeviceStatus* APIUp::add_secondary_device_status() {
  ::SecondaryDeviceStatus* _add = _internal_add_secondary_device_status();
  // @@protoc_insertion_point(field_add:APIUp.secondary_device_status)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::SecondaryDeviceStatus >&
APIUp::secondary_device_status() const {
  // @@protoc_insertion_point(field_list:APIUp.secondary_device_status)
  return secondary_device_status_;
}

// optional string log = 14;
inline bool APIUp::_internal_has_log() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool APIUp::has_log() const {
  return _internal_has_log();
}
inline void APIUp::clear_log() {
  log_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& APIUp::log() const {
  // @@protoc_insertion_point(field_get:APIUp.log)
  return _internal_log();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void APIUp::set_log(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 log_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:APIUp.log)
}
inline std::string* APIUp::mutable_log() {
  std::string* _s = _internal_mutable_log();
  // @@protoc_insertion_point(field_mutable:APIUp.log)
  return _s;
}
inline const std::string& APIUp::_internal_log() const {
  return log_.Get();
}
inline void APIUp::_internal_set_log(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  log_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* APIUp::_internal_mutable_log() {
  _has_bits_[0] |= 0x00000001u;
  return log_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* APIUp::release_log() {
  // @@protoc_insertion_point(field_release:APIUp.log)
  if (!_internal_has_log()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  auto* p = log_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (log_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    log_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void APIUp::set_allocated_log(std::string* log) {
  if (log != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  log_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), log,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (log_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    log_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:APIUp.log)
}

// .ReportFrequency report_frequency = 12;
inline void APIUp::clear_report_frequency() {
  report_frequency_ = 0;
}
inline ::ReportFrequency APIUp::_internal_report_frequency() const {
  return static_cast< ::ReportFrequency >(report_frequency_);
}
inline ::ReportFrequency APIUp::report_frequency() const {
  // @@protoc_insertion_point(field_get:APIUp.report_frequency)
  return _internal_report_frequency();
}
inline void APIUp::_internal_set_report_frequency(::ReportFrequency value) {
  
  report_frequency_ = value;
}
inline void APIUp::set_report_frequency(::ReportFrequency value) {
  _internal_set_report_frequency(value);
  // @@protoc_insertion_point(field_set:APIUp.report_frequency)
}

// uint32 session_id = 15;
inline void APIUp::clear_session_id() {
  session_id_ = 0u;
}
inline uint32_t APIUp::_internal_session_id() const {
  return session_id_;
}
inline uint32_t APIUp::session_id() const {
  // @@protoc_insertion_point(field_get:APIUp.session_id)
  return _internal_session_id();
}
inline void APIUp::_internal_set_session_id(uint32_t value) {
  
  session_id_ = value;
}
inline void APIUp::set_session_id(uint32_t value) {
  _internal_set_session_id(value);
  // @@protoc_insertion_point(field_set:APIUp.session_id)
}

// optional .KcpServerStatus kcp_server_status = 19;
inline bool APIUp::_internal_has_kcp_server_status() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || kcp_server_status_ != nullptr);
  return value;
}
inline bool APIUp::has_kcp_server_status() const {
  return _internal_has_kcp_server_status();
}
inline const ::KcpServerStatus& APIUp::_internal_kcp_server_status() const {
  const ::KcpServerStatus* p = kcp_server_status_;
  return p != nullptr ? *p : reinterpret_cast<const ::KcpServerStatus&>(
      ::_KcpServerStatus_default_instance_);
}
inline const ::KcpServerStatus& APIUp::kcp_server_status() const {
  // @@protoc_insertion_point(field_get:APIUp.kcp_server_status)
  return _internal_kcp_server_status();
}
inline void APIUp::unsafe_arena_set_allocated_kcp_server_status(
    ::KcpServerStatus* kcp_server_status) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(kcp_server_status_);
  }
  kcp_server_status_ = kcp_server_status;
  if (kcp_server_status) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:APIUp.kcp_server_status)
}
inline ::KcpServerStatus* APIUp::release_kcp_server_status() {
  _has_bits_[0] &= ~0x00000002u;
  ::KcpServerStatus* temp = kcp_server_status_;
  kcp_server_status_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::KcpServerStatus* APIUp::unsafe_arena_release_kcp_server_status() {
  // @@protoc_insertion_point(field_release:APIUp.kcp_server_status)
  _has_bits_[0] &= ~0x00000002u;
  ::KcpServerStatus* temp = kcp_server_status_;
  kcp_server_status_ = nullptr;
  return temp;
}
inline ::KcpServerStatus* APIUp::_internal_mutable_kcp_server_status() {
  _has_bits_[0] |= 0x00000002u;
  if (kcp_server_status_ == nullptr) {
    auto* p = CreateMaybeMessage<::KcpServerStatus>(GetArenaForAllocation());
    kcp_server_status_ = p;
  }
  return kcp_server_status_;
}
inline ::KcpServerStatus* APIUp::mutable_kcp_server_status() {
  ::KcpServerStatus* _msg = _internal_mutable_kcp_server_status();
  // @@protoc_insertion_point(field_mutable:APIUp.kcp_server_status)
  return _msg;
}
inline void APIUp::set_allocated_kcp_server_status(::KcpServerStatus* kcp_server_status) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(kcp_server_status_);
  }
  if (kcp_server_status) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(kcp_server_status));
    if (message_arena != submessage_arena) {
      kcp_server_status = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, kcp_server_status, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  kcp_server_status_ = kcp_server_status;
  // @@protoc_insertion_point(field_set_allocated:APIUp.kcp_server_status)
}

inline bool APIUp::has_status() const {
  return status_case() != STATUS_NOT_SET;
}
inline void APIUp::clear_has_status() {
  _oneof_case_[0] = STATUS_NOT_SET;
}
inline APIUp::StatusCase APIUp::status_case() const {
  return APIUp::StatusCase(_oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_public_5fapi_5fup_2eproto
