// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: public_api_down.proto

#include "public_api_down.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
constexpr APIDown::APIDown(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : _oneof_case_{}{}
struct APIDownDefaultTypeInternal {
  constexpr APIDownDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~APIDownDefaultTypeInternal() {}
  union {
    APIDown _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT APIDownDefaultTypeInternal _APIDown_default_instance_;
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_public_5fapi_5fdown_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_public_5fapi_5fdown_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_public_5fapi_5fdown_2eproto = nullptr;

const uint32_t TableStruct_public_5fapi_5fdown_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::APIDown, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::APIDown, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::APIDown, down_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::APIDown)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_APIDown_default_instance_),
};

const char descriptor_table_protodef_public_5fapi_5fdown_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025public_api_down.proto\032\026public_api_type"
  "s.proto\"\367\002\n\007APIDown\022$\n\014base_command\030\001 \001("
  "\0132\014.BaseCommandH\000\0221\n\023linear_lift_command"
  "\030\002 \001(\0132\022.LinearLiftCommandH\000\022\"\n\013arm_comm"
  "and\030\003 \001(\0132\013.ArmCommandH\000\0221\n\023rotate_lift_"
  "command\030\004 \001(\0132\022.RotateLiftCommandH\000\0220\n\024s"
  "et_report_frequency\030\005 \001(\0162\020.ReportFreque"
  "ncyH\000\022;\n\030secondary_device_command\030\007 \001(\0132"
  "\027.SecondaryDeviceCommandH\000\022 \n\nenable_kcp"
  "\030\010 \001(\0132\n.EnableKcpH\000\022\035\n\023placeholder_mess"
  "age\030d \001(\010H\000B\006\n\004downJ\004\010\006\020\007b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_public_5fapi_5fdown_2eproto_deps[1] = {
  &::descriptor_table_public_5fapi_5ftypes_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_public_5fapi_5fdown_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_public_5fapi_5fdown_2eproto = {
  false, false, 433, descriptor_table_protodef_public_5fapi_5fdown_2eproto, "public_api_down.proto", 
  &descriptor_table_public_5fapi_5fdown_2eproto_once, descriptor_table_public_5fapi_5fdown_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_public_5fapi_5fdown_2eproto::offsets,
  file_level_metadata_public_5fapi_5fdown_2eproto, file_level_enum_descriptors_public_5fapi_5fdown_2eproto, file_level_service_descriptors_public_5fapi_5fdown_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_public_5fapi_5fdown_2eproto_getter() {
  return &descriptor_table_public_5fapi_5fdown_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_public_5fapi_5fdown_2eproto(&descriptor_table_public_5fapi_5fdown_2eproto);

// ===================================================================

class APIDown::_Internal {
 public:
  static const ::BaseCommand& base_command(const APIDown* msg);
  static const ::LinearLiftCommand& linear_lift_command(const APIDown* msg);
  static const ::ArmCommand& arm_command(const APIDown* msg);
  static const ::RotateLiftCommand& rotate_lift_command(const APIDown* msg);
  static const ::SecondaryDeviceCommand& secondary_device_command(const APIDown* msg);
  static const ::EnableKcp& enable_kcp(const APIDown* msg);
};

const ::BaseCommand&
APIDown::_Internal::base_command(const APIDown* msg) {
  return *msg->down_.base_command_;
}
const ::LinearLiftCommand&
APIDown::_Internal::linear_lift_command(const APIDown* msg) {
  return *msg->down_.linear_lift_command_;
}
const ::ArmCommand&
APIDown::_Internal::arm_command(const APIDown* msg) {
  return *msg->down_.arm_command_;
}
const ::RotateLiftCommand&
APIDown::_Internal::rotate_lift_command(const APIDown* msg) {
  return *msg->down_.rotate_lift_command_;
}
const ::SecondaryDeviceCommand&
APIDown::_Internal::secondary_device_command(const APIDown* msg) {
  return *msg->down_.secondary_device_command_;
}
const ::EnableKcp&
APIDown::_Internal::enable_kcp(const APIDown* msg) {
  return *msg->down_.enable_kcp_;
}
void APIDown::set_allocated_base_command(::BaseCommand* base_command) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_down();
  if (base_command) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(base_command));
    if (message_arena != submessage_arena) {
      base_command = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, base_command, submessage_arena);
    }
    set_has_base_command();
    down_.base_command_ = base_command;
  }
  // @@protoc_insertion_point(field_set_allocated:APIDown.base_command)
}
void APIDown::clear_base_command() {
  if (_internal_has_base_command()) {
    if (GetArenaForAllocation() == nullptr) {
      delete down_.base_command_;
    }
    clear_has_down();
  }
}
void APIDown::set_allocated_linear_lift_command(::LinearLiftCommand* linear_lift_command) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_down();
  if (linear_lift_command) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(linear_lift_command));
    if (message_arena != submessage_arena) {
      linear_lift_command = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, linear_lift_command, submessage_arena);
    }
    set_has_linear_lift_command();
    down_.linear_lift_command_ = linear_lift_command;
  }
  // @@protoc_insertion_point(field_set_allocated:APIDown.linear_lift_command)
}
void APIDown::clear_linear_lift_command() {
  if (_internal_has_linear_lift_command()) {
    if (GetArenaForAllocation() == nullptr) {
      delete down_.linear_lift_command_;
    }
    clear_has_down();
  }
}
void APIDown::set_allocated_arm_command(::ArmCommand* arm_command) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_down();
  if (arm_command) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(arm_command));
    if (message_arena != submessage_arena) {
      arm_command = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, arm_command, submessage_arena);
    }
    set_has_arm_command();
    down_.arm_command_ = arm_command;
  }
  // @@protoc_insertion_point(field_set_allocated:APIDown.arm_command)
}
void APIDown::clear_arm_command() {
  if (_internal_has_arm_command()) {
    if (GetArenaForAllocation() == nullptr) {
      delete down_.arm_command_;
    }
    clear_has_down();
  }
}
void APIDown::set_allocated_rotate_lift_command(::RotateLiftCommand* rotate_lift_command) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_down();
  if (rotate_lift_command) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(rotate_lift_command));
    if (message_arena != submessage_arena) {
      rotate_lift_command = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, rotate_lift_command, submessage_arena);
    }
    set_has_rotate_lift_command();
    down_.rotate_lift_command_ = rotate_lift_command;
  }
  // @@protoc_insertion_point(field_set_allocated:APIDown.rotate_lift_command)
}
void APIDown::clear_rotate_lift_command() {
  if (_internal_has_rotate_lift_command()) {
    if (GetArenaForAllocation() == nullptr) {
      delete down_.rotate_lift_command_;
    }
    clear_has_down();
  }
}
void APIDown::set_allocated_secondary_device_command(::SecondaryDeviceCommand* secondary_device_command) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_down();
  if (secondary_device_command) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(secondary_device_command));
    if (message_arena != submessage_arena) {
      secondary_device_command = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, secondary_device_command, submessage_arena);
    }
    set_has_secondary_device_command();
    down_.secondary_device_command_ = secondary_device_command;
  }
  // @@protoc_insertion_point(field_set_allocated:APIDown.secondary_device_command)
}
void APIDown::clear_secondary_device_command() {
  if (_internal_has_secondary_device_command()) {
    if (GetArenaForAllocation() == nullptr) {
      delete down_.secondary_device_command_;
    }
    clear_has_down();
  }
}
void APIDown::set_allocated_enable_kcp(::EnableKcp* enable_kcp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_down();
  if (enable_kcp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(enable_kcp));
    if (message_arena != submessage_arena) {
      enable_kcp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, enable_kcp, submessage_arena);
    }
    set_has_enable_kcp();
    down_.enable_kcp_ = enable_kcp;
  }
  // @@protoc_insertion_point(field_set_allocated:APIDown.enable_kcp)
}
void APIDown::clear_enable_kcp() {
  if (_internal_has_enable_kcp()) {
    if (GetArenaForAllocation() == nullptr) {
      delete down_.enable_kcp_;
    }
    clear_has_down();
  }
}
APIDown::APIDown(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:APIDown)
}
APIDown::APIDown(const APIDown& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  clear_has_down();
  switch (from.down_case()) {
    case kBaseCommand: {
      _internal_mutable_base_command()->::BaseCommand::MergeFrom(from._internal_base_command());
      break;
    }
    case kLinearLiftCommand: {
      _internal_mutable_linear_lift_command()->::LinearLiftCommand::MergeFrom(from._internal_linear_lift_command());
      break;
    }
    case kArmCommand: {
      _internal_mutable_arm_command()->::ArmCommand::MergeFrom(from._internal_arm_command());
      break;
    }
    case kRotateLiftCommand: {
      _internal_mutable_rotate_lift_command()->::RotateLiftCommand::MergeFrom(from._internal_rotate_lift_command());
      break;
    }
    case kSetReportFrequency: {
      _internal_set_set_report_frequency(from._internal_set_report_frequency());
      break;
    }
    case kSecondaryDeviceCommand: {
      _internal_mutable_secondary_device_command()->::SecondaryDeviceCommand::MergeFrom(from._internal_secondary_device_command());
      break;
    }
    case kEnableKcp: {
      _internal_mutable_enable_kcp()->::EnableKcp::MergeFrom(from._internal_enable_kcp());
      break;
    }
    case kPlaceholderMessage: {
      _internal_set_placeholder_message(from._internal_placeholder_message());
      break;
    }
    case DOWN_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:APIDown)
}

inline void APIDown::SharedCtor() {
clear_has_down();
}

APIDown::~APIDown() {
  // @@protoc_insertion_point(destructor:APIDown)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void APIDown::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_down()) {
    clear_down();
  }
}

void APIDown::ArenaDtor(void* object) {
  APIDown* _this = reinterpret_cast< APIDown* >(object);
  (void)_this;
}
void APIDown::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void APIDown::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void APIDown::clear_down() {
// @@protoc_insertion_point(one_of_clear_start:APIDown)
  switch (down_case()) {
    case kBaseCommand: {
      if (GetArenaForAllocation() == nullptr) {
        delete down_.base_command_;
      }
      break;
    }
    case kLinearLiftCommand: {
      if (GetArenaForAllocation() == nullptr) {
        delete down_.linear_lift_command_;
      }
      break;
    }
    case kArmCommand: {
      if (GetArenaForAllocation() == nullptr) {
        delete down_.arm_command_;
      }
      break;
    }
    case kRotateLiftCommand: {
      if (GetArenaForAllocation() == nullptr) {
        delete down_.rotate_lift_command_;
      }
      break;
    }
    case kSetReportFrequency: {
      // No need to clear
      break;
    }
    case kSecondaryDeviceCommand: {
      if (GetArenaForAllocation() == nullptr) {
        delete down_.secondary_device_command_;
      }
      break;
    }
    case kEnableKcp: {
      if (GetArenaForAllocation() == nullptr) {
        delete down_.enable_kcp_;
      }
      break;
    }
    case kPlaceholderMessage: {
      // No need to clear
      break;
    }
    case DOWN_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = DOWN_NOT_SET;
}


void APIDown::Clear() {
// @@protoc_insertion_point(message_clear_start:APIDown)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_down();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* APIDown::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .BaseCommand base_command = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_base_command(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .LinearLiftCommand linear_lift_command = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_linear_lift_command(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .ArmCommand arm_command = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_arm_command(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .RotateLiftCommand rotate_lift_command = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_rotate_lift_command(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .ReportFrequency set_report_frequency = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_set_report_frequency(static_cast<::ReportFrequency>(val));
        } else
          goto handle_unusual;
        continue;
      // .SecondaryDeviceCommand secondary_device_command = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          ptr = ctx->ParseMessage(_internal_mutable_secondary_device_command(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .EnableKcp enable_kcp = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          ptr = ctx->ParseMessage(_internal_mutable_enable_kcp(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool placeholder_message = 100;
      case 100:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _internal_set_placeholder_message(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* APIDown::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:APIDown)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .BaseCommand base_command = 1;
  if (_internal_has_base_command()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::base_command(this), target, stream);
  }

  // .LinearLiftCommand linear_lift_command = 2;
  if (_internal_has_linear_lift_command()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::linear_lift_command(this), target, stream);
  }

  // .ArmCommand arm_command = 3;
  if (_internal_has_arm_command()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        3, _Internal::arm_command(this), target, stream);
  }

  // .RotateLiftCommand rotate_lift_command = 4;
  if (_internal_has_rotate_lift_command()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        4, _Internal::rotate_lift_command(this), target, stream);
  }

  // .ReportFrequency set_report_frequency = 5;
  if (_internal_has_set_report_frequency()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      5, this->_internal_set_report_frequency(), target);
  }

  // .SecondaryDeviceCommand secondary_device_command = 7;
  if (_internal_has_secondary_device_command()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        7, _Internal::secondary_device_command(this), target, stream);
  }

  // .EnableKcp enable_kcp = 8;
  if (_internal_has_enable_kcp()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        8, _Internal::enable_kcp(this), target, stream);
  }

  // bool placeholder_message = 100;
  if (_internal_has_placeholder_message()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(100, this->_internal_placeholder_message(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:APIDown)
  return target;
}

size_t APIDown::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:APIDown)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (down_case()) {
    // .BaseCommand base_command = 1;
    case kBaseCommand: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *down_.base_command_);
      break;
    }
    // .LinearLiftCommand linear_lift_command = 2;
    case kLinearLiftCommand: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *down_.linear_lift_command_);
      break;
    }
    // .ArmCommand arm_command = 3;
    case kArmCommand: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *down_.arm_command_);
      break;
    }
    // .RotateLiftCommand rotate_lift_command = 4;
    case kRotateLiftCommand: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *down_.rotate_lift_command_);
      break;
    }
    // .ReportFrequency set_report_frequency = 5;
    case kSetReportFrequency: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_set_report_frequency());
      break;
    }
    // .SecondaryDeviceCommand secondary_device_command = 7;
    case kSecondaryDeviceCommand: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *down_.secondary_device_command_);
      break;
    }
    // .EnableKcp enable_kcp = 8;
    case kEnableKcp: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *down_.enable_kcp_);
      break;
    }
    // bool placeholder_message = 100;
    case kPlaceholderMessage: {
      total_size += 2 + 1;
      break;
    }
    case DOWN_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData APIDown::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    APIDown::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*APIDown::GetClassData() const { return &_class_data_; }

void APIDown::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<APIDown *>(to)->MergeFrom(
      static_cast<const APIDown &>(from));
}


void APIDown::MergeFrom(const APIDown& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:APIDown)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.down_case()) {
    case kBaseCommand: {
      _internal_mutable_base_command()->::BaseCommand::MergeFrom(from._internal_base_command());
      break;
    }
    case kLinearLiftCommand: {
      _internal_mutable_linear_lift_command()->::LinearLiftCommand::MergeFrom(from._internal_linear_lift_command());
      break;
    }
    case kArmCommand: {
      _internal_mutable_arm_command()->::ArmCommand::MergeFrom(from._internal_arm_command());
      break;
    }
    case kRotateLiftCommand: {
      _internal_mutable_rotate_lift_command()->::RotateLiftCommand::MergeFrom(from._internal_rotate_lift_command());
      break;
    }
    case kSetReportFrequency: {
      _internal_set_set_report_frequency(from._internal_set_report_frequency());
      break;
    }
    case kSecondaryDeviceCommand: {
      _internal_mutable_secondary_device_command()->::SecondaryDeviceCommand::MergeFrom(from._internal_secondary_device_command());
      break;
    }
    case kEnableKcp: {
      _internal_mutable_enable_kcp()->::EnableKcp::MergeFrom(from._internal_enable_kcp());
      break;
    }
    case kPlaceholderMessage: {
      _internal_set_placeholder_message(from._internal_placeholder_message());
      break;
    }
    case DOWN_NOT_SET: {
      break;
    }
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void APIDown::CopyFrom(const APIDown& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:APIDown)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool APIDown::IsInitialized() const {
  return true;
}

void APIDown::InternalSwap(APIDown* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(down_, other->down_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata APIDown::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_public_5fapi_5fdown_2eproto_getter, &descriptor_table_public_5fapi_5fdown_2eproto_once,
      file_level_metadata_public_5fapi_5fdown_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::APIDown* Arena::CreateMaybeMessage< ::APIDown >(Arena* arena) {
  return Arena::CreateMessageInternal< ::APIDown >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
