// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: public_api_up.proto

#include "public_api_up.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
constexpr APIUp::APIUp(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : secondary_device_status_()
  , log_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , kcp_server_status_(nullptr)
  , robot_type_(0)

  , report_frequency_(0)

  , protocol_minor_version_(0u)
  , session_id_(0u)
  , protocol_major_version_(0u)
  , _oneof_case_{}{}
struct APIUpDefaultTypeInternal {
  constexpr APIUpDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~APIUpDefaultTypeInternal() {}
  union {
    APIUp _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT APIUpDefaultTypeInternal _APIUp_default_instance_;
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_public_5fapi_5fup_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_public_5fapi_5fup_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_public_5fapi_5fup_2eproto = nullptr;

const uint32_t TableStruct_public_5fapi_5fup_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::APIUp, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::APIUp, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::APIUp, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::APIUp, robot_type_),
  PROTOBUF_FIELD_OFFSET(::APIUp, protocol_major_version_),
  PROTOBUF_FIELD_OFFSET(::APIUp, protocol_minor_version_),
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::APIUp, secondary_device_status_),
  PROTOBUF_FIELD_OFFSET(::APIUp, log_),
  PROTOBUF_FIELD_OFFSET(::APIUp, report_frequency_),
  PROTOBUF_FIELD_OFFSET(::APIUp, session_id_),
  PROTOBUF_FIELD_OFFSET(::APIUp, kcp_server_status_),
  PROTOBUF_FIELD_OFFSET(::APIUp, status_),
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  0,
  ~0u,
  ~0u,
  1,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 19, -1, sizeof(::APIUp)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_APIUp_default_instance_),
};

const char descriptor_table_protodef_public_5fapi_5fup_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023public_api_up.proto\032\026public_api_types."
  "proto\"\206\004\n\005APIUp\022\036\n\nrobot_type\030\001 \001(\0162\n.Ro"
  "botType\022\036\n\026protocol_major_version\030\021 \001(\r\022"
  "\036\n\026protocol_minor_version\030\022 \001(\r\022\"\n\013base_"
  "status\030\002 \001(\0132\013.BaseStatusH\000\022/\n\022linear_li"
  "ft_status\030\003 \001(\0132\021.LinearLiftStatusH\000\022/\n\022"
  "rotate_lift_status\030\005 \001(\0132\021.RotateLiftSta"
  "tusH\000\022 \n\narm_status\030\004 \001(\0132\n.ArmStatusH\000\022"
  "7\n\027secondary_device_status\030\020 \003(\0132\026.Secon"
  "daryDeviceStatus\022\020\n\003log\030\016 \001(\tH\001\210\001\001\022*\n\020re"
  "port_frequency\030\014 \001(\0162\020.ReportFrequency\022\022"
  "\n\nsession_id\030\017 \001(\r\0220\n\021kcp_server_status\030"
  "\023 \001(\0132\020.KcpServerStatusH\002\210\001\001B\010\n\006statusB\006"
  "\n\004_logB\024\n\022_kcp_server_statusJ\004\010\n\020\013J\004\010\013\020\014"
  "J\004\010\r\020\016b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_public_5fapi_5fup_2eproto_deps[1] = {
  &::descriptor_table_public_5fapi_5ftypes_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_public_5fapi_5fup_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_public_5fapi_5fup_2eproto = {
  false, false, 574, descriptor_table_protodef_public_5fapi_5fup_2eproto, "public_api_up.proto", 
  &descriptor_table_public_5fapi_5fup_2eproto_once, descriptor_table_public_5fapi_5fup_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_public_5fapi_5fup_2eproto::offsets,
  file_level_metadata_public_5fapi_5fup_2eproto, file_level_enum_descriptors_public_5fapi_5fup_2eproto, file_level_service_descriptors_public_5fapi_5fup_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_public_5fapi_5fup_2eproto_getter() {
  return &descriptor_table_public_5fapi_5fup_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_public_5fapi_5fup_2eproto(&descriptor_table_public_5fapi_5fup_2eproto);

// ===================================================================

class APIUp::_Internal {
 public:
  using HasBits = decltype(std::declval<APIUp>()._has_bits_);
  static const ::BaseStatus& base_status(const APIUp* msg);
  static const ::LinearLiftStatus& linear_lift_status(const APIUp* msg);
  static const ::RotateLiftStatus& rotate_lift_status(const APIUp* msg);
  static const ::ArmStatus& arm_status(const APIUp* msg);
  static void set_has_log(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::KcpServerStatus& kcp_server_status(const APIUp* msg);
  static void set_has_kcp_server_status(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

const ::BaseStatus&
APIUp::_Internal::base_status(const APIUp* msg) {
  return *msg->status_.base_status_;
}
const ::LinearLiftStatus&
APIUp::_Internal::linear_lift_status(const APIUp* msg) {
  return *msg->status_.linear_lift_status_;
}
const ::RotateLiftStatus&
APIUp::_Internal::rotate_lift_status(const APIUp* msg) {
  return *msg->status_.rotate_lift_status_;
}
const ::ArmStatus&
APIUp::_Internal::arm_status(const APIUp* msg) {
  return *msg->status_.arm_status_;
}
const ::KcpServerStatus&
APIUp::_Internal::kcp_server_status(const APIUp* msg) {
  return *msg->kcp_server_status_;
}
void APIUp::set_allocated_base_status(::BaseStatus* base_status) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_status();
  if (base_status) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(base_status));
    if (message_arena != submessage_arena) {
      base_status = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, base_status, submessage_arena);
    }
    set_has_base_status();
    status_.base_status_ = base_status;
  }
  // @@protoc_insertion_point(field_set_allocated:APIUp.base_status)
}
void APIUp::clear_base_status() {
  if (_internal_has_base_status()) {
    if (GetArenaForAllocation() == nullptr) {
      delete status_.base_status_;
    }
    clear_has_status();
  }
}
void APIUp::set_allocated_linear_lift_status(::LinearLiftStatus* linear_lift_status) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_status();
  if (linear_lift_status) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(linear_lift_status));
    if (message_arena != submessage_arena) {
      linear_lift_status = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, linear_lift_status, submessage_arena);
    }
    set_has_linear_lift_status();
    status_.linear_lift_status_ = linear_lift_status;
  }
  // @@protoc_insertion_point(field_set_allocated:APIUp.linear_lift_status)
}
void APIUp::clear_linear_lift_status() {
  if (_internal_has_linear_lift_status()) {
    if (GetArenaForAllocation() == nullptr) {
      delete status_.linear_lift_status_;
    }
    clear_has_status();
  }
}
void APIUp::set_allocated_rotate_lift_status(::RotateLiftStatus* rotate_lift_status) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_status();
  if (rotate_lift_status) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(rotate_lift_status));
    if (message_arena != submessage_arena) {
      rotate_lift_status = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, rotate_lift_status, submessage_arena);
    }
    set_has_rotate_lift_status();
    status_.rotate_lift_status_ = rotate_lift_status;
  }
  // @@protoc_insertion_point(field_set_allocated:APIUp.rotate_lift_status)
}
void APIUp::clear_rotate_lift_status() {
  if (_internal_has_rotate_lift_status()) {
    if (GetArenaForAllocation() == nullptr) {
      delete status_.rotate_lift_status_;
    }
    clear_has_status();
  }
}
void APIUp::set_allocated_arm_status(::ArmStatus* arm_status) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_status();
  if (arm_status) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(arm_status));
    if (message_arena != submessage_arena) {
      arm_status = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, arm_status, submessage_arena);
    }
    set_has_arm_status();
    status_.arm_status_ = arm_status;
  }
  // @@protoc_insertion_point(field_set_allocated:APIUp.arm_status)
}
void APIUp::clear_arm_status() {
  if (_internal_has_arm_status()) {
    if (GetArenaForAllocation() == nullptr) {
      delete status_.arm_status_;
    }
    clear_has_status();
  }
}
void APIUp::clear_secondary_device_status() {
  secondary_device_status_.Clear();
}
void APIUp::clear_kcp_server_status() {
  if (kcp_server_status_ != nullptr) kcp_server_status_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
APIUp::APIUp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  secondary_device_status_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:APIUp)
}
APIUp::APIUp(const APIUp& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_),
      secondary_device_status_(from.secondary_device_status_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  log_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    log_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_log()) {
    log_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_log(), 
      GetArenaForAllocation());
  }
  if (from._internal_has_kcp_server_status()) {
    kcp_server_status_ = new ::KcpServerStatus(*from.kcp_server_status_);
  } else {
    kcp_server_status_ = nullptr;
  }
  ::memcpy(&robot_type_, &from.robot_type_,
    static_cast<size_t>(reinterpret_cast<char*>(&protocol_major_version_) -
    reinterpret_cast<char*>(&robot_type_)) + sizeof(protocol_major_version_));
  clear_has_status();
  switch (from.status_case()) {
    case kBaseStatus: {
      _internal_mutable_base_status()->::BaseStatus::MergeFrom(from._internal_base_status());
      break;
    }
    case kLinearLiftStatus: {
      _internal_mutable_linear_lift_status()->::LinearLiftStatus::MergeFrom(from._internal_linear_lift_status());
      break;
    }
    case kRotateLiftStatus: {
      _internal_mutable_rotate_lift_status()->::RotateLiftStatus::MergeFrom(from._internal_rotate_lift_status());
      break;
    }
    case kArmStatus: {
      _internal_mutable_arm_status()->::ArmStatus::MergeFrom(from._internal_arm_status());
      break;
    }
    case STATUS_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:APIUp)
}

inline void APIUp::SharedCtor() {
log_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  log_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&kcp_server_status_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&protocol_major_version_) -
    reinterpret_cast<char*>(&kcp_server_status_)) + sizeof(protocol_major_version_));
clear_has_status();
}

APIUp::~APIUp() {
  // @@protoc_insertion_point(destructor:APIUp)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void APIUp::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  log_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete kcp_server_status_;
  if (has_status()) {
    clear_status();
  }
}

void APIUp::ArenaDtor(void* object) {
  APIUp* _this = reinterpret_cast< APIUp* >(object);
  (void)_this;
}
void APIUp::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void APIUp::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void APIUp::clear_status() {
// @@protoc_insertion_point(one_of_clear_start:APIUp)
  switch (status_case()) {
    case kBaseStatus: {
      if (GetArenaForAllocation() == nullptr) {
        delete status_.base_status_;
      }
      break;
    }
    case kLinearLiftStatus: {
      if (GetArenaForAllocation() == nullptr) {
        delete status_.linear_lift_status_;
      }
      break;
    }
    case kRotateLiftStatus: {
      if (GetArenaForAllocation() == nullptr) {
        delete status_.rotate_lift_status_;
      }
      break;
    }
    case kArmStatus: {
      if (GetArenaForAllocation() == nullptr) {
        delete status_.arm_status_;
      }
      break;
    }
    case STATUS_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = STATUS_NOT_SET;
}


void APIUp::Clear() {
// @@protoc_insertion_point(message_clear_start:APIUp)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  secondary_device_status_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      log_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(kcp_server_status_ != nullptr);
      kcp_server_status_->Clear();
    }
  }
  ::memset(&robot_type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&protocol_major_version_) -
      reinterpret_cast<char*>(&robot_type_)) + sizeof(protocol_major_version_));
  clear_status();
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* APIUp::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .RobotType robot_type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_robot_type(static_cast<::RobotType>(val));
        } else
          goto handle_unusual;
        continue;
      // .BaseStatus base_status = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_base_status(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .LinearLiftStatus linear_lift_status = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_linear_lift_status(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .ArmStatus arm_status = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_arm_status(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .RotateLiftStatus rotate_lift_status = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_rotate_lift_status(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .ReportFrequency report_frequency = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 96)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_report_frequency(static_cast<::ReportFrequency>(val));
        } else
          goto handle_unusual;
        continue;
      // optional string log = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 114)) {
          auto str = _internal_mutable_log();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "APIUp.log"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 session_id = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 120)) {
          session_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .SecondaryDeviceStatus secondary_device_status = 16;
      case 16:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 130)) {
          ptr -= 2;
          do {
            ptr += 2;
            ptr = ctx->ParseMessage(_internal_add_secondary_device_status(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<130>(ptr));
        } else
          goto handle_unusual;
        continue;
      // uint32 protocol_major_version = 17;
      case 17:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 136)) {
          protocol_major_version_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 protocol_minor_version = 18;
      case 18:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 144)) {
          protocol_minor_version_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .KcpServerStatus kcp_server_status = 19;
      case 19:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 154)) {
          ptr = ctx->ParseMessage(_internal_mutable_kcp_server_status(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* APIUp::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:APIUp)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .RobotType robot_type = 1;
  if (this->_internal_robot_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_robot_type(), target);
  }

  // .BaseStatus base_status = 2;
  if (_internal_has_base_status()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::base_status(this), target, stream);
  }

  // .LinearLiftStatus linear_lift_status = 3;
  if (_internal_has_linear_lift_status()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        3, _Internal::linear_lift_status(this), target, stream);
  }

  // .ArmStatus arm_status = 4;
  if (_internal_has_arm_status()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        4, _Internal::arm_status(this), target, stream);
  }

  // .RotateLiftStatus rotate_lift_status = 5;
  if (_internal_has_rotate_lift_status()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        5, _Internal::rotate_lift_status(this), target, stream);
  }

  // .ReportFrequency report_frequency = 12;
  if (this->_internal_report_frequency() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      12, this->_internal_report_frequency(), target);
  }

  // optional string log = 14;
  if (_internal_has_log()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_log().data(), static_cast<int>(this->_internal_log().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "APIUp.log");
    target = stream->WriteStringMaybeAliased(
        14, this->_internal_log(), target);
  }

  // uint32 session_id = 15;
  if (this->_internal_session_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(15, this->_internal_session_id(), target);
  }

  // repeated .SecondaryDeviceStatus secondary_device_status = 16;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_secondary_device_status_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(16, this->_internal_secondary_device_status(i), target, stream);
  }

  // uint32 protocol_major_version = 17;
  if (this->_internal_protocol_major_version() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(17, this->_internal_protocol_major_version(), target);
  }

  // uint32 protocol_minor_version = 18;
  if (this->_internal_protocol_minor_version() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(18, this->_internal_protocol_minor_version(), target);
  }

  // optional .KcpServerStatus kcp_server_status = 19;
  if (_internal_has_kcp_server_status()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        19, _Internal::kcp_server_status(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:APIUp)
  return target;
}

size_t APIUp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:APIUp)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .SecondaryDeviceStatus secondary_device_status = 16;
  total_size += 2UL * this->_internal_secondary_device_status_size();
  for (const auto& msg : this->secondary_device_status_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional string log = 14;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_log());
    }

    // optional .KcpServerStatus kcp_server_status = 19;
    if (cached_has_bits & 0x00000002u) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *kcp_server_status_);
    }

  }
  // .RobotType robot_type = 1;
  if (this->_internal_robot_type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_robot_type());
  }

  // .ReportFrequency report_frequency = 12;
  if (this->_internal_report_frequency() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_report_frequency());
  }

  // uint32 protocol_minor_version = 18;
  if (this->_internal_protocol_minor_version() != 0) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_protocol_minor_version());
  }

  // uint32 session_id = 15;
  if (this->_internal_session_id() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32SizePlusOne(this->_internal_session_id());
  }

  // uint32 protocol_major_version = 17;
  if (this->_internal_protocol_major_version() != 0) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_protocol_major_version());
  }

  switch (status_case()) {
    // .BaseStatus base_status = 2;
    case kBaseStatus: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *status_.base_status_);
      break;
    }
    // .LinearLiftStatus linear_lift_status = 3;
    case kLinearLiftStatus: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *status_.linear_lift_status_);
      break;
    }
    // .RotateLiftStatus rotate_lift_status = 5;
    case kRotateLiftStatus: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *status_.rotate_lift_status_);
      break;
    }
    // .ArmStatus arm_status = 4;
    case kArmStatus: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *status_.arm_status_);
      break;
    }
    case STATUS_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData APIUp::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    APIUp::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*APIUp::GetClassData() const { return &_class_data_; }

void APIUp::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<APIUp *>(to)->MergeFrom(
      static_cast<const APIUp &>(from));
}


void APIUp::MergeFrom(const APIUp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:APIUp)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  secondary_device_status_.MergeFrom(from.secondary_device_status_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_log(from._internal_log());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_mutable_kcp_server_status()->::KcpServerStatus::MergeFrom(from._internal_kcp_server_status());
    }
  }
  if (from._internal_robot_type() != 0) {
    _internal_set_robot_type(from._internal_robot_type());
  }
  if (from._internal_report_frequency() != 0) {
    _internal_set_report_frequency(from._internal_report_frequency());
  }
  if (from._internal_protocol_minor_version() != 0) {
    _internal_set_protocol_minor_version(from._internal_protocol_minor_version());
  }
  if (from._internal_session_id() != 0) {
    _internal_set_session_id(from._internal_session_id());
  }
  if (from._internal_protocol_major_version() != 0) {
    _internal_set_protocol_major_version(from._internal_protocol_major_version());
  }
  switch (from.status_case()) {
    case kBaseStatus: {
      _internal_mutable_base_status()->::BaseStatus::MergeFrom(from._internal_base_status());
      break;
    }
    case kLinearLiftStatus: {
      _internal_mutable_linear_lift_status()->::LinearLiftStatus::MergeFrom(from._internal_linear_lift_status());
      break;
    }
    case kRotateLiftStatus: {
      _internal_mutable_rotate_lift_status()->::RotateLiftStatus::MergeFrom(from._internal_rotate_lift_status());
      break;
    }
    case kArmStatus: {
      _internal_mutable_arm_status()->::ArmStatus::MergeFrom(from._internal_arm_status());
      break;
    }
    case STATUS_NOT_SET: {
      break;
    }
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void APIUp::CopyFrom(const APIUp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:APIUp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool APIUp::IsInitialized() const {
  return true;
}

void APIUp::InternalSwap(APIUp* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  secondary_device_status_.InternalSwap(&other->secondary_device_status_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &log_, lhs_arena,
      &other->log_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(APIUp, protocol_major_version_)
      + sizeof(APIUp::protocol_major_version_)
      - PROTOBUF_FIELD_OFFSET(APIUp, kcp_server_status_)>(
          reinterpret_cast<char*>(&kcp_server_status_),
          reinterpret_cast<char*>(&other->kcp_server_status_));
  swap(status_, other->status_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata APIUp::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_public_5fapi_5fup_2eproto_getter, &descriptor_table_public_5fapi_5fup_2eproto_once,
      file_level_metadata_public_5fapi_5fup_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::APIUp* Arena::CreateMaybeMessage< ::APIUp >(Arena* arena) {
  return Arena::CreateMessageInternal< ::APIUp >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
